variables:
  APP_PATH: '$CI_PROJECT_DIR'
  OUTPUT_PATH: '$CI_PROJECT_DIR/out'

deploy_dev:
  only:
    - dev
  environment:
    name: production
  variables:
    API_TOKEN: $DEPLOYMENT_TOKEN
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."

deploy:
  only:
    - main
  environment:
    name: production
  variables:
    API_TOKEN: $DEPLOYMENT_TOKEN
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
