import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import HomeIndex from "@/components/Home/HomeIndex";
const inter = Inter({ subsets: ["latin"] });
import "regenerator-runtime/runtime.js";

export default function Home() {
  return (
    <div className="bg-white">
      <Head>
        <title>Chargocheck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
        <HomeIndex />
      </div>
      <Footer />
    </div>
  );
}
